# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.NodeHierarchy')),
            ],
        ),
    ]
