# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeHierarchy',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField(max_length=10, null=True)),
                ('input_code', models.CharField(max_length=20)),
                ('node_order', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'PARAM'), (1, 'PATH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=50)),
                ('port', models.IntegerField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'DELETE')], default=0)),
                ('version', models.CharField(max_length=40)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.NodeHierarchy')),
            ],
        ),
        migrations.AddField(
            model_name='param',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.TestCase'),
        ),
    ]
