# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostPort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_port', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NodeHierarchy',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('parent_id', models.IntegerField(null=True)),
                ('input_code', models.CharField(max_length=20)),
                ('node_order', models.IntegerField()),
                ('node_type', models.IntegerField(choices=[(2, '叶子节点'), (1, '子节点'), (0, '根节点')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('real_result', models.CharField(max_length=40)),
                ('test_result', models.BooleanField()),
                ('execute_date', models.DateField()),
                ('execute', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('method', models.IntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'DELETE')], default=0)),
                ('expect_result', models.CharField(max_length=40)),
                ('host_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.HostPort')),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.NodeHierarchy')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.Version'),
        ),
        migrations.AddField(
            model_name='result',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.TestCase'),
        ),
    ]
