# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodehierarchy',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='port',
            field=models.IntegerField(),
        ),
    ]
