# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0002_auto_20170518_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodehierarchy',
            name='node_order',
            field=models.IntegerField(),
        ),
    ]
