# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('f', models.ManyToManyField(to='user.Boy')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, 'man'), (1, 'weman')], default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserType'),
        ),
        migrations.AddField(
            model_name='b2g',
            name='boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Boy'),
        ),
        migrations.AddField(
            model_name='b2g',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Girl'),
        ),
    ]
