# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('result', models.IntegerField(choices=[(0, '失败'), (1, '成功'), (2, '无结果')], default=0)),
                ('return_data', models.CharField(max_length=500)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.TestCase')),
            ],
        ),
    ]
